function dyt = dynamic3(i,y)
%*********************************************************************
% Constants
%*********************************************************************
m0      = 136077.7;% Takeoff weight;
omegae = 0.00007292;
rearth = 6.38E6;
h = 0.01;

%*********************************************************************
% Assigning Variables
%*********************************************************************
V1(i) = y(1);  gamma1(i)= y(2);   chi1(i)  = y(3);
h1(i) = y(4);  phi1(i)  = y(5);   theta1(i)= y(6);
mf(i) = y(7);   

psiV(i) = y(8);    psigamma(i) = y(9);    psichi(i)  = y(10);
psih(i) = y(11);   psiphi(i)   = y(12);   psitheta(i)  = y(13);
psim(i) = y(14);

alfa(i) = alpha_equation(V1(i),psiV(i),psigamma(i));
[D,Y,L,Dv,Yv,Lv,g,rho] = aero([V1(i) h1(i) alfa(i)]);
[Thrust,Thrustd,I] = thrust([V1(i) g rho]);
F = [D Y L];      F_v = [Dv Yv Lv]; 

% ********************************************************
% Estimation of Position
% ********************************************************
R(i) = h1(i) + rearth;
h1(i+1)     = h1(i) + h*V1(i)*sin(gamma1(i));
phi1(i+1)   = phi1(i) + h*V1(i)*cos(gamma1(i))*cos(chi1(i))/R;
theta1(i+1) = theta1(i) + h*V1(i)*cos(gamma1(i))*sin(chi1(i))/(R*cos(phi1(i)));

% ***************************************************************
% Mass Consuming Equation 
% ***************************************************************

CT = 0.0005.*(V1(i)/305).^4 - 0.0221.*(V1(i)/305).^3 + 0.2763.*(V1(i)/305).^2 -...
    0.8517.*(V1(i)/305) + 1.0619;
mf(i+1) = mf(i) - h*(0.80823*rho*V1(i)*CT);
m(i) = m0 - mf(i+1); 

% ***************************************************************
% Set up of Right Hand Side Eauations
% ***************************************************************

D = F(1); Y = F(2); L = F(3); mu = 0; 

V1(i+1)= V1(i) + h*((Thrust-D)/m(i))-g*sin(gamma1(i))+omegae^2*R*cos(phi1(i))^2*...
    (sin(gamma1(i))-cos(gamma1(i))*tan(phi1(i))*sin(chi1(i)));
gamma1(i+1)= gamma1(i) + h*(1/V1(i))*((L*cos(mu)-Y*sin(mu))/m(i) - g*cos(gamma1(i))+(V1(i)^2*...
    cos(gamma1(i)))/R+2*omegae*V1(i)*cos(phi1(i))*cos(chi1(i))+omegae^2*R*...
    cos(phi1(i))^2*(cos(gamma1(i))+sin(gamma1(i))*tan(phi1(i))*sin(chi1(i))));
chi1(i+1) = chi1(i) + h*(1/V1(i))*((L*sin(mu)+Y*cos(mu))/(m(i)*cos(gamma1(i)))-(V1(i)^2/R)*cos(gamma1(i))...
    *cos(chi1(i))*tan(phi1(i))+2*omegae*V1(i)*(tan(gamma1(i))*cos(phi1(i))*sin(chi1(i))...
    -sin(phi1(i)))-(omegae^2*R/cos(gamma1(i)))*sin(phi1(i))*cos(phi1(i))*cos(chi1(i)));

%****************************************************************
% Alpha Costate 7 Differential Equations  
%**************************************************************** 
Dv = F_v(1); Yv = F_v(2); Lv = F_v(3);

psiV(i+1) = psiV(i) + h*(-psiV(i)*(1/m(i))*(Thrustd-Dv) - psigamma(i)*((1/(m(i)*V1(i)))*Lv +...
    cos(gamma1(i))/R + (1/V1(i)^2)*(g*cos(gamma1(i))-R*omegae^2*cos(phi1(i))^2*...
    (sin(gamma1(i))*tan(phi1(i))*sin(chi1(i))+cos(gamma1(i)))-L/m(i)))-psichi(i)*...
    (-cos(gamma1(i))*tan(phi1(i))*cos(chi1(i))/R + (omegae^2*R*sin(phi1(i))*...
    cos(phi1(i))*cos(chi1(i)))/(cos(gamma1(i))*V1(i)^2))...
    - psih(i)*sin(gamma1(i)) - psiphi(i)*...
    (cos(gamma1(i))*cos(chi1(i))/R) - psitheta(i)*(cos(gamma1(i))*sin(chi1(i))/...
    (R*cos(phi1(i)))));

psigamma(i+1) = psigamma(i) + h*(-psiV(i)*(-g*cos(gamma1(i))+R*omegae^2*cos(phi1(i))^2*(sin(gamma1(i))*...
    tan(phi1(i))*sin(chi1(i))+cos(gamma1(i)))) - psigamma(i)*(R*omegae^2*cos(phi1(i))...
    ^2*(cos(gamma1(i))*tan(phi1(i))*sin(chi1(i))-sin(gamma1(i)))/V1(i)+sin(gamma1(i))*...
    (g/V1(i)-V1(i)/R)) - psichi(i)*(-R*omegae^2*sin(phi1(i))*cos(phi1(i))*cos(chi1(i))*...
    sin(gamma1(i))/(V1(i)*cos(gamma1(i))^2)+2*omegae*cos(phi1(i))*sin(chi1(i))*...
    (tan(gamma1(i))^2+1)+V1(i)*sin(gamma1(i))*cos(chi1(i))*tan(phi1(i))/R) - psih(i)*...
    (V1(i)*cos(gamma1(i))) + psiphi(i)*...
    (V1(i)*sin(gamma1(i))*cos(chi1(i))/R) + psitheta(i)*(V1(i)*sin(gamma1(i))*sin(chi1(i))/...
    (R*cos(phi1(i)))));

psichi(i+1) = psichi(i) + h*(psiV(i)*(R*omegae^2*cos(phi1(i))^2*cos(gamma1(i))*tan(phi1(i))*cos(chi1(i)))-...
    psigamma(i)*(-2*omegae*cos(phi1(i))*sin(chi1(i))+R*omegae^2*cos(phi1(i))^2*...
    sin(gamma1(i))*tan(phi1(i))*cos(chi1(i))/V1(i)) - psichi(i)*(V1(i)*cos(gamma1(i))*...
    sin(chi1(i))*tan(phi1(i))/R+2*omegae*tan(gamma1(i))*cos(phi1(i))*cos(chi1(i))+...
    omegae^2*R*sin(phi1(i))*cos(phi1(i))*sin(chi1(i))/(V1(i)*cos(gamma1(i)))) +...
    psiphi(i)*(V1(i)*cos(gamma1(i))*...
    sin(chi1(i))/R) - psitheta(i)*(V1(i)*cos(gamma1(i))*cos(chi1(i))/(R*cos(phi1(i)))));

psih(i+1) = psih(i) + h*(-psiV(i)*(omegae^2*cos(phi1(i))^2*(-cos(gamma1(i))*tan(phi1(i))*sin(chi1(i))+...
    sin(gamma1(i)))) - psigamma(i)*(-V1(i)*cos(gamma1(i))/R^2+omegae^2*cos(phi1(i))^2*(...
    cos(gamma1(i))+sin(gamma1(i))*tan(phi1(i))*sin(chi1(i)))) - psichi(i)*(V1(i)*cos(...
    gamma1(i))*cos(chi1(i))*tan(phi1(i))/R^2-omegae^2*sin(phi1(i))*cos(phi1(i))*...
    cos(chi1(i))/(V1(i)*cos(gamma1(i)))) + psiphi(i)*(V1(i)*cos(gamma1(i))*cos(chi1(i))/R^2)...
    + psitheta(i)*(V1(i)*cos(gamma1(i))*cos(chi1(i))/(R^2*cos(phi1(i)))));

psiphi(i+1) = psiphi(i) + h*(-psiV(i)*R*omegae^2*(-cos(gamma1(i))*sin(phi1(i))^2*sin(chi1(i))+2*...
    cos(gamma1(i))*sin(phi1(i))^2*sin(chi1(i))-cos(gamma1(i))*cos(phi1(i))^2*sin(chi1(i))-...
    sin(gamma1(i))*sin(2*phi1(i))) - psigamma(i)*(-2*omegae*sin(phi1(i))*cos(chi1(i))...
    +(R*omegae^2/V1(i))*(-sin(2*phi1(i))*cos(gamma1(i))-sin(2*phi1(i))*sin(gamma1(i))*...
    tan(phi1(i))*sin(chi1(i))+cos(phi1(i))^2*sin(gamma1(i))*sin(chi1(i))+sin(phi1(i))^2*...
    sin(gamma1(i))*sin(chi1(i)))) - psichi(i)*(-V1(i)*cos(gamma1(i))*cos(chi1(i))*(tan...
    (phi1(i))^2+1)/R-2*omegae*(tan(gamma1(i))*sin(phi1(i))*sin(chi1(i))+cos(phi1(i)))...
    +R*omegae^2*cos(chi1(i))*(sin(phi1(i))^2-cos(phi1(i))^2)/(V1(i)*cos(gamma1(i)))) +...
    psitheta(i)*(V1(i)*cos(gamma1(i))*sin(chi1(i))*sin(phi1(i))/(R*cos(phi1(i))^2)));

psitheta(i+1) = psitheta(i) + 0;

psim(i+1) = psim(i) + h*(- psiV(i)*((-Thrust+D)/m(i)^2) + psigamma(i)*(L/(V1(i)*m(i)^2)));

dyt = [V1(i+1),gamma1(i+1),chi1(i+1),h1(i+1),phi1(i+1),theta1(i+1),...
    mf(i+1),psiV(i+1),psigamma(i+1),psichi(i+1),psih(i+1),psiphi(i+1),...
    psitheta(i+1),psim(i+1)];

% ***************************************************************
% End of Sub Program RHS
% ***************************************************************
