function JAK = Jak(F,F_v,g,rho,Thrust,Thrustd,I,m,omegae)
D = F(1); Y = F(2); L = F(3);  Dv = F_v(1); Yv = F_v(2); Lv = F_v(3);
mu = 0;

syms V1 gamma1 chi1 R phi1 theta1 mf psiV psigamma psichi psiphi psitheta psih psim

V1d=((Thrust-D)/m)-g*sin(gamma1)+omegae^2*R*cos(phi1)^2*...
    (sin(gamma1)-cos(gamma1)*tan(phi1)*sin(chi1));
gammad=(1/V1)*((L*cos(mu)-Y*sin(mu))/m - g*cos(gamma1)+(V1^2*...
    cos(gamma1))/R+2*omegae*V1*cos(phi1)*cos(chi1)+omegae^2*R*...
    cos(phi1)^2*(cos(gamma1)+sin(gamma1)*tan(phi1)*sin(chi1)));
chid=(1/V1)*((L*sin(mu)+Y*cos(mu))/(m*cos(gamma1))-(V1^2/R)*cos(gamma1)...
    *cos(chi1)*tan(phi1)+2*omegae*V1*(tan(gamma1)*cos(phi1)*sin(chi1)...
    -sin(phi1))-(omegae^2*R/cos(gamma1))*sin(phi1)*cos(phi1)*cos(chi1));

h1p     = V1*sin(gamma1);
phi1p   = V1*cos(gamma1)*cos(chi1)/R;
theta1p = V1*cos(gamma1)*sin(chi1)/(R*cos(phi1));

mfd = - 0.029*rho*V1*27.87*(0.0005.*(V1/305).^4 - 0.0221.*(V1/305).^3 +...
    0.2763.*(V1/305).^2 - 0.8517.*(V1/305) + 1.0619);

psiVd = -psiV*(1/m)*(Thrustd-Dv) - psigamma*((1/(m*V1))*Lv +...
    cos(gamma1)/R + (1/V1^2)*(g*cos(gamma1)-R*omegae^2*cos(phi1)^2*...
    (sin(gamma1)*tan(phi1)*sin(chi1)+cos(gamma1))-L/m))-psichi*...
    (-cos(gamma1)*tan(phi1)*cos(chi1)/R + (omegae^2*R*sin(phi1)*...
    cos(phi1)*cos(chi1))/(cos(gamma1)*V1^2))...
    - psih*sin(gamma1) - psiphi*...
    (cos(gamma1)*cos(chi1)/R) - psitheta*(cos(gamma1)*sin(chi1)/...
    (R*cos(phi1)));

psigammad = -psiV*(-g*cos(gamma1)+R*omegae^2*cos(phi1)^2*(sin(gamma1)*...
    tan(phi1)*sin(chi1)+cos(gamma1))) - psigamma*(R*omegae^2*cos(phi1)...
    ^2*(cos(gamma1)*tan(phi1)*sin(chi1)-sin(gamma1))/V1+sin(gamma1)*...
    (g/V1-V1/R)) - psichi*(-R*omegae^2*sin(phi1)*cos(phi1)*cos(chi1)*...
    sin(gamma1)/(V1*cos(gamma1)^2)+2*omegae*cos(phi1)*sin(chi1)*...
    (tan(gamma1)^2+1)+V1*sin(gamma1)*cos(chi1)*tan(phi1)/R) - psih*...
    (V1*cos(gamma1)) + psiphi*...
    (V1*sin(gamma1)*cos(chi1)/R) + psitheta*(V1*sin(gamma1)*sin(chi1)/...
    (R*cos(phi1)));

psichid = psiV*(R*omegae^2*cos(phi1)^2*cos(gamma1)*tan(phi1)*cos(chi1))-...
    psigamma*(-2*omegae*cos(phi1)*sin(chi1)+R*omegae^2*cos(phi1)^2*...
    sin(gamma1)*tan(phi1)*cos(chi1)/V1) - psichi*(V1*cos(gamma1)*...
    sin(chi1)*tan(phi1)/R+2*omegae*tan(gamma1)*cos(phi1)*cos(chi1)+...
    omegae^2*R*sin(phi1)*cos(phi1)*sin(chi1)/(V1*cos(gamma1))) +...
    psiphi*(V1*cos(gamma1)*...
    sin(chi1)/R) - psitheta*(V1*cos(gamma1)*cos(chi1)/(R*cos(phi1)));

psihd = -psiV*(omegae^2*cos(phi1)^2*(-cos(gamma1)*tan(phi1)*sin(chi1)+...
    sin(gamma1))) - psigamma*(-V1*cos(gamma1)/R^2+omegae^2*cos(phi1)^2*(...
    cos(gamma1)+sin(gamma1)*tan(phi1)*sin(chi1))) - psichi*(V1*cos(...
    gamma1)*cos(chi1)*tan(phi1)/R^2-omegae^2*sin(phi1)*cos(phi1)*...
    cos(chi1)/(V1*cos(gamma1))) + psiphi*(V1*cos(gamma1)*cos(chi1)/R^2)...
    + psitheta*(V1*cos(gamma1)*cos(chi1)/(R^2*cos(phi1)));

psiphid = -psiV*R*omegae^2*(-cos(gamma1)*sin(phi1)^2*sin(chi1)+2*...
    cos(gamma1)*sin(phi1)^2*sin(chi1)-cos(gamma1)*cos(phi1)^2*sin(chi1)-...
    sin(gamma1)*sin(2*phi1)) - psigamma*(-2*omegae*sin(phi1)*cos(chi1)...
    +(R*omegae^2/V1)*(-sin(2*phi1)*cos(gamma1)-sin(2*phi1)*sin(gamma1)*...
    tan(phi1)*sin(chi1)+cos(phi1)^2*sin(gamma1)*sin(chi1)+sin(phi1)^2*...
    sin(gamma1)*sin(chi1))) - psichi*(-V1*cos(gamma1)*cos(chi1)*(tan...
    (phi1)^2+1)/R-2*omegae*(tan(gamma1)*sin(phi1)*sin(chi1)+cos(phi1))...
    +R*omegae^2*cos(chi1)*(sin(phi1)^2-cos(phi1)^2)/(V1*cos(gamma1))) +...
    psitheta*(V1*cos(gamma1)*sin(chi1)*sin(phi1)/(R*cos(phi1)^2));

psithetad = 0;

psimd = - psiV*((-Thrust+D)/m^2) + psigamma*(L/(V1*m^2));

% DV = [V1d gammad chid h1p phi1p theta1p mfd psiVd psigammad psichid psihd psiphid psithetad psimd]';
% 
% JAK = jacobian(DV, [V1,gamma1,chi1,R,phi1,theta1,mf,psiV,psigamma,psichi,psih,psiphi,psitheta,psim]);

% DV = [V1d gammad chid h1p phi1p theta1p mfd psiVd psigammad psichid psihd psiphid psithetad psimd]';
JAK = [diff(V1d,V1)        diff(V1d,gamma1)        diff(V1d,chi1)        diff(V1d,R)        diff(V1d,phi1)                0                       0                         0                        0                        0                          0                       0             diff(V1d,theta1)        diff(V1d,mf);
       diff(gammad,V1)     diff(gammad,gamma1)     diff(gammad,chi1)     diff(gammad,R)     diff(gammad,phi1)             0                       0                         0                        0                        0                          0                       0             diff(gammad,theta1)     diff(gammad,mf);
       diff(chid,V1)       diff(chid,gamma1)       diff(chid,chi1)       diff(chid,R)       diff(chid,phi1)               0                       0                         0                        0                        0                          0                       0             diff(chid,theta1)       diff(chid,mf);
       diff(h1p,V1)        diff(h1p,gamma1)        diff(h1p,chi1)        diff(h1p,R)        diff(h1p,phi1)                0                       0                         0                        0                        0                          0                       0             diff(h1p,theta1)        diff(h1p,mf);
       diff(phi1p,V1)      diff(phi1p,gamma1)      diff(phi1p,chi1)      diff(phi1p,R)      diff(phi1p,phi1)              0                       0                         0                        0                        0                          0                       0             diff(phi1p,theta1)      diff(phi1p,mf);
       diff(psiVd,V1)      diff(psiVd,gamma1)      diff(psiVd,chi1)      diff(psiVd,R)      diff(psiVd,phi1)       diff(psiVd,psiV)       diff(psiVd,psigamma)       diff(psiVd,psichi)       diff(psiVd,psih)       diff(psiVd,psiphi)       diff(psiVd,psim)       diff(psiVd,psitheta)     diff(psiVd,theta1)      diff(psiVd,mf);
       diff(psigammad,V1)  diff(psigammad,gamma1)  diff(psigammad,chi1)  diff(psigammad,R)  diff(psigammad,phi1)  diff(psigammad,psiV)   diff(psigammad,psigamma)   diff(psigammad,psichi)   diff(psigammad,psih)   diff(psigammad,psiphi)    diff(psigammad,psim)   diff(psigammad,psitheta)  diff(psigammad,theta1)         0    ;
       diff(psichid,V1)    diff(psichid,gamma1)    diff(psichid,chi1)    diff(psichid,R)    diff(psichid,phi1)    diff(psichid,psiV)     diff(psichid,psigamma)     diff(psichid,psichi)     diff(psichid,psih)     diff(psichid,psiphi)      diff(psichid,psim)     diff(psichid,psitheta)    diff(psichid,theta1)           0    ; 
       diff(psihd,V1)      diff(psihd,gamma1)      diff(psihd,chi1)      diff(psihd,R)      diff(psihd,phi1)      diff(psihd,psiV)       diff(psihd,psigamma)       diff(psihd,psichi)       diff(psihd,psih)       diff(psihd,psiphi)        diff(psihd,psim)       diff(psihd,psitheta)      diff(psihd,theta1)             0    ;
       diff(psiphid,V1)    diff(psiphid,gamma1)    diff(psiphid,chi1)    diff(psiphid,R)    diff(psiphid,phi1)    diff(psiphid,psiV)     diff(psiphid,psigamma)     diff(psiphid,psichi)     diff(psiphid,psih)     diff(psiphid,psiphi)      diff(psiphid,psim)     diff(psiphid,psitheta)    diff(psiphid,theta1)           0    ;
       diff(psimd,V1)      diff(psimd,gamma1)      diff(psimd,chi1)      diff(psimd,R)      diff(psimd,phi1)      diff(psimd,psiV)       diff(psimd,psigamma)       diff(psimd,psichi)       diff(psimd,psih)       diff(psimd,psiphi)        diff(psimd,psim)       diff(psimd,psitheta)      diff(psimd,theta1)      diff(psimd,mf);
       diff(psithetad,V1)  diff(psithetad,gamma1)  diff(psithetad,chi1)  diff(psithetad,R)  diff(psithetad,phi1)  diff(psithetad,psiV)   diff(psithetad,psigamma)   diff(psithetad,psichi)   diff(psithetad,psih)   diff(psithetad,psiphi)    diff(psithetad,psim)   diff(psithetad,psitheta)  diff(psithetad,theta1)         0    ;
       diff(theta1p,V1)    diff(theta1p,gamma1)    diff(theta1p,chi1)    diff(theta1p,R)    diff(theta1p,phi1)            0                       0                         0                        0                        0                          0                       0             diff(theta1p,theta1)    diff(theta1p,mf);
       diff(mfd,V1)        diff(mfd,gamma1)        diff(mfd,chi1)        diff(mfd,R)        diff(mfd,phi1)                0                       0                         0                        0                        0                          0                       0             diff(mfd,theta1)        diff(mfd,mf)];

